import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Layout from '@/components/Layout';
import QuickLinks from '@/components/QuickLinks';
import '@/styles/globals.css';
import Head from 'next/head';
import { useRouter } from 'next/router';

const normalUserPages = [
  '/',
  'index/',
  '/contact',
  '/gallery',
  '/about',
  '/admissions',
  '/news',
];

export default function App({ Component, pageProps }) {
  const router = useRouter();

  const isNormalUserPage = normalUserPages.includes(router.pathname);
  return (
    <>
      <Head>
        <title>Maasai Education Center - the Style Hotel Schoo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300,400&display=swap"
          rel="stylesheet"
        />{' '} */}
      </Head>
      {isNormalUserPage && (
        <>
          <QuickLinks />
          <Header />
        </>
      )}
      <Layout>
        <Component {...pageProps} />
      </Layout>
      {isNormalUserPage && <Footer />}
    </>
  );
}
